name: text_gen_guided
channels:
  - conda-forge       # always first on FASRC
  - nvidia            # for pytorch-cuda
  - pytorch
dependencies:
  # core
  - python=3.9
  - pip
  - pytorch=2.2.2
  - torchvision=0.17.2
  - pytorch-cuda=12.1      # GPU
  # tooling
  - jupyterlab             # newer Jupyter front-end
  - git-lfs
  # extras pulled by conda where possible
  - pandas=2.2.*
  - seaborn=0.13.*
  - scikit-learn=1.4.*
  # everything else via pip
  - pip:
      - datasets==2.18.0
      - einops==0.7.0
      - fsspec==2024.2.0
      - h5py==3.10.0
      - hydra-core==1.3.2
      - ipdb==0.13.13
      - lightning==2.2.1
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - packaging==23.2
      - rich==13.7.1
      - timm==0.9.16
      - transformers==4.38.2
      - wandb==0.13.5
      # optional GPU-only builds
      #- flash-attn==2.5.6      # GPU
      ##- triton==2.2.0          # GPU